FROM node:22-alpine
WORKDIR /app
ENV DATABASE_URL=postgresql://postgres:postgres@localhost:5432/appdb
RUN apk add --no-cache openssl
COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm install --ignore-scripts
COPY docker/entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh
RUN chmod +x /usr/local/bin/entrypoint.dev.sh
EXPOSE 3000
ENTRYPOINT ["/usr/local/bin/entrypoint.dev.sh"]
CMD ["npm", "run", "dev"]
