FROM node:22-alpine
WORKDIR /app
ENV DATABASE_URL=postgresql://postgres:postgres@localhost:5432/appdb
RUN apk add --no-cache openssl
COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm install --ignore-scripts
COPY . .
RUN npm run prisma:generate
EXPOSE 3000
CMD ["sh", "-c", "npm run prisma:migrate:deploy && npm run dev"]
